// 잠실 롯데월드타워 반경 1km 카페 데이터
export const CAFES = [
  { id: 'c1', name: '인텔리젠시아커피 잠실점', category: '스페셜티커피', rating: 4.6, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c2', name: '노티드월드', category: '카페/도넛', rating: 4.5, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c3', name: '베질루르 선셋에비뉴 월드타워점', category: '카페/밀크티', rating: 4.2, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c4', name: 'CONNECT TO', category: '카페/디저트', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c5', name: '니커버커 베이글', category: '카페/베이글', rating: 4.5, price: '₩₩', distance: '송리단길' },
  { id: 'c7', name: '위커파크', category: '카페', rating: 4.2, price: '₩₩', distance: '석촌호수' },
  { id: 'c8', name: '카페 이클립스', category: '테라스카페', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c9', name: '슬로우어스 (SLOWUS)', category: '브런치카페', rating: 4.4, price: '₩₩', distance: '석촌호수' },
  { id: 'c10', name: '몽가 (Mongga)', category: '브런치카페', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c11', name: '진저베어', category: '브런치/디저트', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c12', name: '웰하우스', category: '디저트카페', rating: 4.6, price: '₩₩', distance: '석촌호수' },
  { id: 'c13', name: '디저티스트', category: '디저트카페', rating: 4.3, price: '₩₩', distance: '송리단길' },
  { id: 'c14', name: '겟썸커피', category: '커피', rating: 4.4, price: '₩₩', distance: '석촌호수' },
  { id: 'c15', name: '뷰클런즈', category: '카페', rating: 4.3, price: '₩₩', distance: '송리단길' },
  { id: 'c16', name: '가배도', category: '카페', rating: 4.4, price: '₩₩', distance: '송리단길' },
  { id: 'c17', name: '매트블랙커피 롯데월드몰점', category: '카페', rating: 4.4, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c18', name: '엔제리너스X윤쉐프 정직한제빵소 잠실롯데월드몰점', category: '카페/베이커리', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c19', name: '카페시나몬', category: '카페/베이커리', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c20', name: '엔제리너스 샤롯데점', category: '카페', rating: 4.2, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c21', name: '컨플릭트스토어', category: '카페/스페셜티커피', rating: 4.5, price: '₩₩₩', distance: '잠실역' },
  { id: 'c22', name: '교토퍼펙트말차 잠실롯데월드몰점', category: '디저트/말차', rating: 4.4, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c23', name: '폴바셋 롯데월드 아이스링크점', category: '카페', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c24', name: '백미당', category: '카페/아이스크림', rating: 4.4, price: '₩₩', distance: '롯데백화점' },
  { id: 'c25', name: '아우프글렛', category: '카페/베이커리', rating: 4.2, price: '₩₩', distance: '롯데백화점' },
  { id: 'c26', name: '헤리터', category: '디저트카페', rating: 4.3, price: '₩₩', distance: '롯데백화점' },
  { id: 'c27', name: '보난자커피 로스터스', category: '스페셜티커피', rating: 4.3, price: '₩₩', distance: '롯데백화점' },
  { id: 'c28', name: '카페이페메라', category: '카페', rating: 4.2, price: '₩₩', distance: '롯데백화점' },
  { id: 'c29', name: '아메리칸트레일러', category: '브런치카페', rating: 4.3, price: '₩₩', distance: '롯데백화점' },
  { id: 'c30', name: '파스퇴르 밀크바', category: '카페/밀크티', rating: 4.2, price: '₩₩', distance: '롯데백화점' },
  { id: 'c31', name: '123젤라또', category: '젤라또', rating: 4.3, price: '₩₩', distance: '롯데백화점' },
  { id: 'c32', name: '메종라꽁비에뜨', category: '카페/베이커리', rating: 4.4, price: '₩₩', distance: '롯데백화점' },
  { id: 'c33', name: '고디바 베이커리', category: '디저트카페', rating: 4.3, price: '₩₩', distance: '롯데백화점' },
  { id: 'c34', name: '노아스로스팅카페', category: '스페셜티커피', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c35', name: '슈퍼말차카페', category: '디저트/말차', rating: 4.2, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c36', name: '아쿠아가든카페', category: '카페', rating: 4.1, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c37', name: '뮬리노에스프레소바', category: '스페셜티커피', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c38', name: '고호재', category: '전통찻집', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c39', name: '카페페퍼', category: '디저트카페', rating: 4.5, price: '₩₩', distance: '송리단길' },
  { id: 'c40', name: '포모르', category: '브런치카페', rating: 4.4, price: '₩₩', distance: '송리단길' },
  { id: 'c41', name: '니드스윗', category: '카페', rating: 4.2, price: '₩₩', distance: '송리단길' },
];
