// 잠실 롯데월드타워 반경 1km 카페 데이터
export const CAFES = [
  { id: 'c1', name: '인텔리젠시아커피 잠실점', category: '스페셜티커피', rating: 4.6, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c2', name: '노티드월드', category: '카페/도넛', rating: 4.5, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c3', name: '베질루르 선셋에비뉴 월드타워점', category: '카페/밀크티', rating: 4.2, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c4', name: 'CONNECT TO', category: '카페/디저트', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c5', name: '니커버커 베이글', category: '카페/베이글', rating: 4.5, price: '₩₩', distance: '송리단길' },
  { id: 'c7', name: '위커파크', category: '카페', rating: 4.2, price: '₩₩', distance: '석촌호수' },
  { id: 'c8', name: '카페 이클립스', category: '테라스카페', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c9', name: '슬로우어스 (SLOWUS)', category: '브런치카페', rating: 4.4, price: '₩₩', distance: '석촌호수' },
  { id: 'c10', name: '몽가 (Mongga)', category: '브런치카페', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c11', name: '진저베어', category: '브런치/디저트', rating: 4.3, price: '₩₩', distance: '석촌호수' },
  { id: 'c12', name: '웰하우스', category: '디저트카페', rating: 4.6, price: '₩₩', distance: '석촌호수' },
  { id: 'c13', name: '디저티스트', category: '디저트카페', rating: 4.3, price: '₩₩', distance: '송리단길' },
  { id: 'c14', name: '겟썸커피', category: '커피', rating: 4.4, price: '₩₩', distance: '석촌호수' },
  { id: 'c15', name: '뷰클런즈', category: '카페', rating: 4.3, price: '₩₩', distance: '송리단길' },
  { id: 'c16', name: '가배도', category: '카페', rating: 4.4, price: '₩₩', distance: '송리단길' },
  { id: 'c17', name: '매트블랙커피 롯데월드몰점', category: '카페', rating: 4.4, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c18', name: '엔제리너스X윤쉐프 정직한제빵소 잠실롯데월드몰점', category: '카페/베이커리', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c19', name: '카페시나몬', category: '카페/베이커리', rating: 4.3, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c20', name: '엔제리너스 샤롯데점', category: '카페', rating: 4.2, price: '₩₩', distance: '롯데월드몰' },
  { id: 'c21', name: '컨플릭트스토어', category: '카페/스페셜티커피', rating: 4.5, price: '₩₩₩', distance: '잠실역' },
  { id: 'c22', name: '교토퍼펙트말차 잠실롯데월드몰점', category: '디저트/말차', rating: 4.4, price: '₩₩', distance: '롯데월드몰' },
];
