// 잠실 방이동/송리단길 회식(고깃집·술집) 데이터 — restaurants.ts와 별도 관리
export const GROUP_VENUES = [
  { id: 'g1', name: '고도식', category: '고기/구이', rating: 4.7, price: '₩₩₩', distance: '송리단길' },
  { id: 'g2', name: '숙수돈가', category: '고기/구이', rating: 4.6, price: '₩₩₩', distance: '송리단길' },
  { id: 'g3', name: '한티옥', category: '한식/보쌈', rating: 4.9, price: '₩₩₩', distance: '방이동' },
  { id: 'g4', name: '송돝', category: '고기/구이', rating: 4.6, price: '₩₩₩', distance: '방이동' },
  { id: 'g5', name: '화덕고깃간', category: '고기/삼겹살', rating: 4.6, price: '₩₩₩', distance: '방이동' },
  { id: 'g6', name: '모토쿠라시', category: '이자카야', rating: 4.5, price: '₩₩₩', distance: '송리단길' },
  { id: 'g7', name: '사케쇼프', category: '이자카야', rating: 4.6, price: '₩₩₩', distance: '송리단길' },
  { id: 'g8', name: '팔각동', category: '이자카야', rating: 4.4, price: '₩₩₩', distance: '송리단길' },
  { id: 'g9', name: '이자카야 토라', category: '이자카야', rating: 4.4, price: '₩₩₩', distance: '방이동' },
  { id: 'g10', name: '야키토리잔잔 방이점', category: '이자카야/야키토리', rating: 4.3, price: '₩₩₩', distance: '방이동' },
  { id: 'g11', name: '부엉이산장 방이점', category: '한식주점', rating: 4.4, price: '₩₩', distance: '방이동' },
  { id: 'g12', name: '제일곱창 방이직영점', category: '고기/곱창', rating: 4.5, price: '₩₩₩', distance: '방이동' },
  { id: 'g13', name: '방이돈가', category: '고기/삼겹살', rating: 4.5, price: '₩₩₩', distance: '방이동' },
  { id: 'g14', name: '방이옥 본점', category: '고기/우대갈비', rating: 4.4, price: '₩₩₩', distance: '방이동' },
  { id: 'g15', name: '와르르맨숀 방이점', category: '한식주점', rating: 4.3, price: '₩₩', distance: '방이동' },
  { id: 'g16', name: '육몽 방이직영점', category: '고기/구이', rating: 4.3, price: '₩₩₩', distance: '방이동' },
  { id: 'g17', name: '일월고기', category: '고기/삼겹살', rating: 4.4, price: '₩₩₩', distance: '방이동' },
  { id: 'g18', name: '일월껍데기', category: '고기/껍데기', rating: 4.3, price: '₩₩₩', distance: '방이동' },
  { id: 'g19', name: '형제애', category: '중식/음주중식', rating: 4.5, price: '₩₩₩', distance: '방이동' },
  { id: 'g20', name: '소뭉집 방이직영점', category: '한식/육회', rating: 4.4, price: '₩₩₩', distance: '방이동' },
  { id: 'g21', name: '무교낙지해물탕', category: '한식/해물탕', rating: 4.3, price: '₩₩₩', distance: '방이동' },
  { id: 'g22', name: '텍사스로드하우스 잠실본점', category: '양식/스테이크', rating: 4.5, price: '₩₩₩', distance: '방이동' },
  { id: 'g23', name: '강촌식당 방이점', category: '한식/닭갈비', rating: 4.4, price: '₩₩', distance: '방이동' },
  { id: 'g24', name: '청선 방이본점', category: '고기/구이', rating: 4.4, price: '₩₩₩', distance: '방이동' },
  { id: 'g25', name: '굽돌집 잠실방이직영점', category: '고기/구이', rating: 4.3, price: '₩₩₩', distance: '방이동' },
  { id: 'g26', name: '메종성수돈 송파점', category: '고기/돼지고기', rating: 4.4, price: '₩₩₩', distance: '송파' },
  { id: 'g27', name: '마스타하이볼', category: '바/하이볼', rating: 4.4, price: '₩₩', distance: '방이동' },
  { id: 'g28', name: '나쉬펍 잠실방이점', category: '바/맥주', rating: 4.4, price: '₩₩', distance: '방이동' },
  { id: 'g29', name: '쥬크박스', category: '바/맥주', rating: 4.4, price: '₩₩', distance: '방이동' },
];
