// 잠실 롯데월드몰/백화점 맛집 데이터
export const RESTAURANTS = [
  { id: '1', name: '유미분분식', category: '분식', rating: 4.4, price: '₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '2', name: '만옥', category: '중식', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '3', name: '쌤쌤쌤 (Sam Sam Sam)', category: '양식', rating: 4.7, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '4', name: '포브라더스', category: '아시안', rating: 4.5, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '5', name: '고봉삼계탕', category: '한식', rating: 4.6, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '6', name: '구워주는집', category: '고기/구이', rating: 4.5, price: '₩₩', distance: '롯데백화점', isSoloFriendly: false },
  { id: '7', name: '하이디라오 훠궈', category: '중식/훠궈', rating: 4.8, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '8', name: '바이킹스 워프', category: '해산물 뷔페', rating: 4.7, price: '₩₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '10', name: '해목', category: '일식/덮밥', rating: 4.3, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '11', name: '오레노라멘 롯데월드몰점', category: '일식/라멘', rating: 4.4, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '12', name: '치즈룸&테이스팅룸', category: '양식', rating: 4.6, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '13', name: '갓덴스시', category: '일식/스시', rating: 4.5, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '14', name: '빌즈 (Bills)', category: '양식/브런치', rating: 4.2, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '15', name: '온더보더', category: '멕시칸', rating: 4.1, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '16', name: '피에프창', category: '중식/아시안', rating: 4.3, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '17', name: '칸다소바', category: '일식/마제소바', rating: 4.5, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '18', name: '브루클린 더 버거 조인트', category: '양식/버거', rating: 4.4, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '19', name: '쉑쉑버거', category: '양식/버거', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '20', name: '아그라', category: '인도음식', rating: 4.4, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '21', name: '스페인클럽', category: '스페인음식', rating: 4.1, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '22', name: '차이797', category: '중식', rating: 4.2, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '23', name: '부탄츄', category: '일식/라멘', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '25', name: '미미네', category: '분식', rating: 4.1, price: '₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '26', name: '코코이찌방야', category: '일식/카레', rating: 4.2, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '27', name: '사이드쇼', category: '분식/떡볶이', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '28', name: '리틀사이공', category: '베트남음식', rating: 4.2, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '29', name: '강가', category: '인도음식', rating: 4.3, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '31', name: '베테랑칼국수', category: '한식/칼국수', rating: 4.2, price: '₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '32', name: '라 세느 (La Seine)', category: '호텔뷔페', rating: 4.3, price: '₩₩₩₩', distance: '롯데호텔', isSoloFriendly: false },
  { id: '33', name: '땀땀', category: '베트남음식', rating: 4.1, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '34', name: '한국집', category: '한식/비빔밥', rating: 4.0, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '35', name: '마즈야', category: '일식/돈까스', rating: 4.1, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '36', name: '봉피양', category: '한식/냉면', rating: 4.4, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '37', name: '다이치', category: '일식/돈까스', rating: 4.2, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '41', name: '대치동함흥면옥', category: '한식/냉면', rating: 4.1, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '43', name: '촙촙 (Chop Chop)', category: '아시안/베트남', rating: 4.2, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '45', name: '딤딤섬', category: '중식/딤섬', rating: 4.3, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '46', name: '런던 베이글 뮤지엄 잠실점', category: '베이커리/브런치', rating: 4.5, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '47', name: '디라이프스타일키친', category: '양식/파스타', rating: 4.4, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '48', name: '서령 롯데월드몰점', category: '한식/냉면', rating: 4.5, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '49', name: '오사이초밥 잠실송리단길점', category: '일식/스시 오마카세', rating: 4.5, price: '₩₩', distance: '송리단길', isSoloFriendly: true },
  { id: '51', name: '크리스탈제이드', category: '중식/상하이요리', rating: 4.3, price: '₩₩₩₩', distance: '롯데백화점', isSoloFriendly: false },
  { id: '52', name: '엠스테이크하우스', category: '양식/스테이크', rating: 4.3, price: '₩₩₩₩', distance: '롯데백화점', isSoloFriendly: false },
  { id: '53', name: '렌위치 롯데월드몰점', category: '샌드위치/샐러드', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '54', name: '마루가메우동 롯데월드몰점', category: '일식/우동', rating: 4.3, price: '₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '55', name: '지강한식당 잠실점', category: '한식', rating: 4.3, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '56', name: '서보', category: '태국음식', rating: 4.5, price: '₩₩', distance: '송리단길', isSoloFriendly: true },
  { id: '57', name: '금금', category: '퓨전한식', rating: 4.6, price: '₩₩₩', distance: '송리단길', isSoloFriendly: true },
  { id: '58', name: '본디', category: '고기/구이', rating: 4.7, price: '₩₩₩', distance: '송리단길', isSoloFriendly: false },
  { id: '59', name: '김태완스시', category: '일식/스시', rating: 4.4, price: '₩₩', distance: '송리단길', isSoloFriendly: true },
  { id: '60', name: '이랑칼국수', category: '한식/닭한마리', rating: 4.5, price: '₩₩', distance: '송리단길', isSoloFriendly: false },
  { id: '61', name: '완도산회 포장마차', category: '해산물/횟집', rating: 4.3, price: '₩₩', distance: '송리단길', isSoloFriendly: false },
  { id: '62', name: '몽촌닭갈비', category: '한식/닭갈비', rating: 4.5, price: '₩₩', distance: '석촌호수', isSoloFriendly: false },
  { id: '63', name: '프로티너 잠실방이점', category: '샐러드/헬시푸드', rating: 4.3, price: '₩₩', distance: '방이동', isSoloFriendly: true },
  { id: '64', name: '매드포갈릭 롯데캐슬 잠실점', category: '양식/이탈리안', rating: 4.2, price: '₩₩₩', distance: '잠실역', isSoloFriendly: false },
  { id: '65', name: '교토퍼펙트말차 잠실롯데월드몰점', category: '디저트/말차', rating: 4.4, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '66', name: '팬트리12 롯데월드타워점', category: '샌드위치', rating: 4.2, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: true },
  { id: '67', name: '난포 롯데월드몰', category: '한식', rating: 4.5, price: '₩₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '68', name: '금수복국 잠실소피텔점', category: '한식/복어', rating: 4.4, price: '₩₩₩', distance: '잠실역', isSoloFriendly: true },
  { id: '69', name: '방이순대국', category: '한식/순대국', rating: 4.3, price: '₩', distance: '방이동', isSoloFriendly: true },
  { id: '70', name: '샛집남원추어탕', category: '한식/추어탕', rating: 4.4, price: '₩₩', distance: '방이동', isSoloFriendly: true },
  { id: '71', name: '등촌샤브칼국수 방이본점', category: '한식/칼국수', rating: 4.4, price: '₩₩', distance: '방이동', isSoloFriendly: true },
  { id: '72', name: '동대문닭한마리', category: '한식/닭한마리', rating: 4.2, price: '₩₩₩', distance: '방이동', isSoloFriendly: false },
  { id: '73', name: '육전국밥 석촌호수점', category: '한식/국밥', rating: 4.4, price: '₩', distance: '석촌호수', isSoloFriendly: true },
  { id: '74', name: '오뎅식당 롯데월드몰점', category: '한식/부대찌개', rating: 4.4, price: '₩₩', distance: '롯데월드몰', isSoloFriendly: false },
  { id: '75', name: '이태리부대찌개 잠실역점', category: '한식/부대찌개', rating: 4.2, price: '₩₩', distance: '잠실역', isSoloFriendly: false },
  { id: '76', name: '수가성', category: '한식/순두부', rating: 4.3, price: '₩₩', distance: '잠실역', isSoloFriendly: true },
  { id: '77', name: '연남토마 롯데캐슬 잠실점', category: '일식/돈까스', rating: 4.3, price: '₩₩', distance: '잠실역', isSoloFriendly: true },
  { id: '78', name: '고복 롯데백화점 잠실점 캐슬플라자', category: '중식', rating: 4.2, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '79', name: '계도 롯데백화점 잠실', category: '한식', rating: 4.2, price: '₩₩', distance: '롯데백화점', isSoloFriendly: true },
  { id: '80', name: '삼우정 잠실본점', category: '한식/불고기', rating: 4.4, price: '₩₩₩', distance: '롯데백화점', isSoloFriendly: false },
];
